name: Hello world workflow

on:
  push:
  branches:
  - main
pull_request:
  branches:
  - main
workflow_dispatch:
  
  
jobs:
  hello:
  runs-on: ubuntu-latest
  steps:
   - uses: kumar05061995/coss/checkou 
   - name: hello world
     run:  echo "hello world"
     shell: bash
     

  
  
  
